python run_simplification.py \
    --model_name_or_path t5-small \
    --do_train \
    --do_eval \
    --dataset_name wikilarge \
    --source_prefix "summarize: " \
    --output_dir /tmp/tst-summarization \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir \
    --predict_with_generate \
    --eval_steps 10 \
    --evaluation_strategy steps
